Repository christianhelle/refitter, pull requests merged in 2023-10, with the labels that each got.

#172 Allow for custom relative output path in .refitter
  README.md
  src/Refitter.Core/RefitGeneratorSettings.cs
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/SwaggerPetstoreCustomOutputFolder.refitter
  src/Refitter.SourceGenerator.Tests/CustomGenerated/SwaggerPetstoreCustomOutputFolder.g.cs
  src/Refitter.SourceGenerator.Tests/CustomOutputFolderGeneratorTests.cs
  src/Refitter.SourceGenerator/README.md
  src/Refitter.SourceGenerator/RefitterSourceGenerator.cs
Labels: enhancement

#181 Allow method name customization when generating multiple interfaces by endpoint
  README.md
  src/Refitter.Core/RefitGeneratorSettings.cs
  src/Refitter.Core/RefitMultipleInterfaceGenerator.cs
  src/Refitter.Tests/SwaggerPetstoreTests.cs
  src/Refitter/GenerateCommand.cs
  src/Refitter/README.md
  src/Refitter/Settings.cs
  test/smoke-tests.ps1
Labels: enhancement

#183 Use Internal types to improve docfx documentation generation
  src/Refitter.Core/DependencyInjectionGenerator.cs
  src/Refitter.Core/OperationNameGenerator.cs
  src/Refitter.Core/ParameterExtractor.cs
  src/Refitter.Core/RefitGeneratedCode.cs
  src/Refitter.Core/RefitInterfaceImports.cs
  src/Refitter.Core/Refitter.Core.csproj
  src/Refitter.Core/StringCasingExtensions.cs
  src/Refitter.Core/WellKnownNamesspaces.cs
Labels: documentation, enhancement

#188 Add support for customizable type and contract generator settings
  README.md
  docs/docfx_project/articles/refitter-file-format.md
  src/Refitter.Core/CSharpClientGeneratorFactory.cs
  src/Refitter.Core/Serializer.cs
  src/Refitter.Core/Settings/CodeGeneratorSettings.cs
  src/Refitter.Core/Settings/DependencyInjectionSettings.cs
  src/Refitter.Core/Settings/MultipleInterfaces.cs
  src/Refitter.Core/Settings/NamingSettings.cs
  src/Refitter.Core/Settings/RefitGeneratorSettings.cs
  src/Refitter.Core/Settings/TypeAccessibility.cs
  src/Refitter.SourceGenerator/README.md
  src/Refitter.SourceGenerator/Refitter.SourceGenerator.csproj
  src/Refitter.SourceGenerator/RefitterSourceGenerator.cs
  src/Refitter.Tests/CustomCSharpGeneratorSettingsTests.cs
  src/Refitter.Tests/Examples/CustomCodeGeneratorWithDateTimeTests.cs
  src/Refitter.Tests/Refitter.Tests.csproj
  src/Refitter.Tests/SerializerTests.cs
  src/Refitter/Analytics.cs
  src/Refitter/GenerateCommand.cs
  test/petstore.refitter
Labels: enhancement

#197 Remove `namespace` settings from `codeGeneratorSettings`
  README.md
  docs/docfx_project/articles/refitter-file-format.md
  src/Refitter.Core/Settings/CodeGeneratorSettings.cs
  src/Refitter.Core/Settings/RefitGeneratorSettings.cs
  src/Refitter.SourceGenerator/README.md
  src/Refitter/README.md
Labels: bug

#201 Add JetBrains Qodana GitHub workflow
  .github/workflows/qodana.yml
Labels: enhancement

#202 Enable JetBrains Qodana auto-fixes
  .github/workflows/qodana.yml
  qodana.yml
Labels: enhancement

#200 Output filename customization
  .github/workflows/qodana.yml
  README.md
  docs/docfx_project/articles/refitter-file-format.md
  src/Refitter.Core/Serializer.cs
  src/Refitter.Core/Settings/DependencyInjectionSettings.cs
  src/Refitter.Core/Settings/MultipleInterfaces.cs
  src/Refitter.Core/Settings/NamingSettings.cs
  src/Refitter.Core/Settings/RefitGeneratorSettings.cs
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/SwaggerPetstoreCustomOutputFolder.refitter
  src/Refitter.SourceGenerator.Tests/CustomGenerated/CustomGenerated.cs
  src/Refitter.SourceGenerator.Tests/CustomOutputFolderGeneratorTests.cs
  src/Refitter.SourceGenerator/README.md
  src/Refitter.SourceGenerator/RefitterSourceGenerator.cs
  src/Refitter/GenerateCommand.cs
  src/Refitter/README.md
  src/Refitter/Settings.cs
  src/Refitter/SettingsValidator.cs
  test/petstore.refitter
  test/smoke-tests.ps1
Labels: enhancement

#207 Fix extra close paranthesis in IServiceCollectionExtensions
  src/Refitter.Core/DependencyInjectionGenerator.cs
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreMultipleInterfaces.g.cs
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreSingleInterface.g.cs
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/SwaggerPetstoreMultipleInterfaces.refitter
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/SwaggerPetstoreSingleInterface.refitter
  src/Refitter.SourceGenerator.Tests/DelegatingHandlers.cs
  src/Refitter.SourceGenerator.Tests/Refitter.SourceGenerator.Tests.csproj
  test/SourceGenerator/Directory.Build.props
Labels: bug, enhancement
