Repository christianhelle/refitter, pull requests merged in 2024-09, with the labels that each got.

#452 Enable nullable annotations and disable warnings
  src/Refitter.Core/RefitGenerator.cs
Labels: enhancement

#455 Handle '%' in property names
  src/Refitter.Core/CustomCSharpPropertyNameGenerator.cs
  src/Refitter.Tests/Examples/PercentageCharacterTests.cs
Labels: enhancement, .NET

#462 Added setting UsePolymorphicSerialization
  src/Refitter.Core/CSharpClientGeneratorFactory.cs
  src/Refitter.Core/CustomCSharpClientGenerator.cs
  src/Refitter.Core/Refitter.Core.csproj
  src/Refitter.Core/Settings/RefitGeneratorSettings.cs
  src/Refitter.Core/Templates/Class.liquid
  src/Refitter.Core/Templates/JsonInheritanceAttribute.liquid
  src/Refitter.Core/Templates/JsonInheritanceConverter.liquid
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/UseJsonInheritanceConverter.g.cs
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/UsePolymorphicSerialization.g.cs
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/UseJsonInheritanceConverter.refitter
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/UsePolymorphicSerialization.refitter
  src/Refitter.SourceGenerator.Tests/Refitter.SourceGenerator.Tests.csproj
  src/Refitter.SourceGenerator.Tests/Resources/UsePolymorphicSerialization.yaml
  src/Refitter.SourceGenerator.Tests/UseJsonInheritanceConverterTests.cs
  src/Refitter.SourceGenerator.Tests/UsePolymorphicSerializationTests.cs
  src/Refitter.SourceGenerator/Refitter.SourceGenerator.csproj
  src/Refitter.Tests/Examples/UsePolymorphicSerializationTests.cs
  src/Refitter/GenerateCommand.cs
  src/Refitter/Settings.cs
Labels: enhancement

#465 added IgnoreUnrecognizedTypeDiscriminators = true
  src/Refitter.Core/Templates/Class.liquid
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/UsePolymorphicSerialization.g.cs
  src/Refitter.Tests/Examples/UsePolymorphicSerializationTests.cs
Labels: enhancement

#466 Add basic documentation for Polymorphic Serialization
  README.md
  docs/docfx_project/articles/refitter-file-format.md
  src/Refitter/README.md
  src/Refitter/Settings.cs
Labels: documentation

#470 use-polymorphic-serialization docs
  README.md
  docs/docfx_project/articles/cli-tool.md
  docs/docfx_project/articles/refitter-file-format.md
  docs/docfx_project/articles/using-the-generated-code.md
  src/Refitter.SourceGenerator/README.md
Labels: documentation

#490 Use Azure App Insights for telemetry
  src/Refitter/Analytics.cs
  src/Refitter/Refitter.csproj
  src/Refitter/SupportKeyInitializer.cs
Labels: enhancement, .NET
