Repository christianhelle/refitter, pull requests merged in 2024-02, with the labels that each got.

#314 JSON schema
  docs/docfx_project/articles/refitter-file-format.md
  docs/json-schema.json
Labels: documentation

#322 Generating IObservable type response
  src/Refitter.Core/RefitInterfaceGenerator.cs
  src/Refitter.Core/RefitInterfaceImports.cs
  src/Refitter.Core/Settings/RefitGeneratorSettings.cs
  src/Refitter.Tests/SwaggerPetstoreTests.cs
  src/Refitter/GenerateCommand.cs
  src/Refitter/Settings.cs
Labels: enhancement, .NET

#326 IObservable<T> improvements
  .github/workflows/template.yml
  README.md
  docs/docfx_project/articles/cli-tool.md
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/Refitter.g.cs
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreOptionalParameters.g.cs
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreSingleInterface.g.cs
  src/Refitter.Tests/Build/ProjectFileContents.cs
  src/Refitter.Tests/SwaggerPetstoreTests.cs
  src/Refitter/README.md
  test/ConsoleApp/Directory.Build.props
  test/ConsoleApp/Program.cs
  test/smoke-tests.ps1
Labels: documentation, enhancement, .NET

#327 Change license to MIT
  LICENSE
  src/Directory.Build.props
Labels: documentation
