Repository christianhelle/refitter, pull requests merged in 2024-11, with the labels that each got.

#539 [Apizr] Deprecated Optional package removed from code & doc
  src/Refitter.Core/ApizrRegistrationGenerator.cs
  src/Refitter.Core/Settings/ApizrPackages.cs
  src/Refitter.Core/Settings/ApizrSettings.cs
  src/Refitter.SourceGenerator/README.md
  src/Refitter.Tests/ApizrGeneratorWithMicrosoftHttpResilienceTests.cs
  src/Refitter.Tests/ApizrGeneratorWithPollyTests.cs
  src/Refitter.Tests/Build/ProjectFileContents.cs
  src/Refitter.Tests/SwaggerPetstoreApizrTests.cs
  src/Refitter.Tests/SwaggerPetstoreTests.cs
  src/Refitter/README.md
Labels: documentation, enhancement

#541 Clients implementing IDisposable interface
  src/Refitter.Core/RefitInterfaceGenerator.cs
  src/Refitter.Core/RefitInterfaceImports.cs
  src/Refitter.Core/Settings/RefitGeneratorSettings.cs
Labels: enhancement, .NET

#543 Generate IDisposable Refit Interfaces
  README.md
  docs/docfx_project/articles/cli-tool.md
  docs/docfx_project/articles/refitter-file-format.md
  docs/json-schema.json
  src/Refitter.Core/RefitInterfaceGenerator.cs
  src/Refitter.Core/RefitInterfaceImports.cs
  src/Refitter.SourceGenerator/README.md
  src/Refitter.Tests/SwaggerPetstoreMultipleFileTests.cs
  src/Refitter.Tests/SwaggerPetstoreTests.cs
  src/Refitter/GenerateCommand.cs
  src/Refitter/README.md
  src/Refitter/Settings.cs
  test/smoke-tests.ps1
Labels: documentation, enhancement, .NET
