Repository christianhelle/refitter, pull requests merged in 2024-01, with the labels that each got.

#260 Add support for OAS files with external references
  .github/workflows/smoke-tests.yml
  .github/workflows/template.yml
  src/Refitter/GenerateCommand.cs
  src/Refitter/Merger/OpenApiMerger.cs
  src/Refitter/Merger/OpenApiMissingReferenceVisitor.cs
  src/Refitter/Merger/OpenApiReferenceResolverVisitor.cs
  src/Refitter/Merger/ReferenceCache.cs
  src/Refitter/OAS/OpenApiReader.cs
  src/Refitter/Refitter.csproj
  src/Refitter/Validation/OpenApiValidator.cs
  test/OpenAPI/v3.0/bot.components.yaml
  test/OpenAPI/v3.0/bot.paths.yaml
  test/smoke-tests.ps1
Labels: enhancement

#267 Use OasReader library for loading OAS documents with external references
  src/Makefile
  src/Refitter.Core/DependencyInjectionGenerator.cs
  src/Refitter.Core/OpenApiDocumentFactory.cs
  src/Refitter.Core/ParameterExtractor.cs
  src/Refitter.Core/RefitGenerator.cs
  src/Refitter.Core/Refitter.Core.csproj
  src/Refitter.SourceGenerator/Refitter.SourceGenerator.csproj
  src/Refitter.Tests/OpenApiDocumentFactoryTests.cs
  src/Refitter/GenerateCommand.cs
  src/Refitter/Merger/OpenApiMerger.cs
  src/Refitter/Merger/OpenApiMissingReferenceVisitor.cs
  src/Refitter/Merger/OpenApiReferenceResolverVisitor.cs
  src/Refitter/Merger/ReferenceCache.cs
  src/Refitter/OAS/OpenApiReader.cs
  src/Refitter/Refitter.csproj
  src/Refitter/Validation/OpenApiValidator.cs
Labels: enhancement

#272 Configurable IOperationNameGenerator implementations
  README.md
  docs/docfx_project/articles/cli-tool.md
  src/Refitter.Core/CSharpClientGeneratorFactory.cs
  src/Refitter.Core/OperationNameGenerator.cs
  src/Refitter.Core/RefitInterfaceGenerator.cs
  src/Refitter.Core/Settings/OperationNameGeneratorTypes.cs
  src/Refitter.Core/Settings/RefitGeneratorSettings.cs
  src/Refitter.Core/StringCasingExtensions.cs
  src/Refitter.Tests/StringCasingExtensionTests.cs
  src/Refitter.Tests/SwaggerPetstoreTests.cs
  src/Refitter/GenerateCommand.cs
  src/Refitter/README.md
  src/Refitter/Settings.cs
Labels: enhancement

#273 Update --operation-name-generator options documentation
  README.md
  docs/docfx_project/articles/cli-tool.md
  docs/docfx_project/articles/refitter-file-format.md
  src/Refitter/README.md
  src/Refitter/Settings.cs
Labels: documentation

#274 Add new options to .refitter file format docs
  README.md
  docs/docfx_project/articles/refitter-file-format.md
  src/Refitter/README.md
Labels: documentation

#278 Serialize OperationNameGenerator enum as string
  src/Refitter.Core/Settings/RefitGeneratorSettings.cs
  test/petstore.refitter
Labels: enhancement, .NET, bugfix

#279 Fix type accessibility deserialization.
  src/Refitter.Core/Settings/RefitGeneratorSettings.cs
Labels: enhancement, .NET

#281 Provide more extensive method documentation.
  README.md
  src/Refitter.Core/RefitGenerator.cs
  src/Refitter.Core/RefitInterfaceGenerator.cs
  src/Refitter.Core/RefitMultipleInterfaceByTagGenerator.cs
  src/Refitter.Core/RefitMultipleInterfaceGenerator.cs
  src/Refitter.Core/Settings/RefitGeneratorSettings.cs
  src/Refitter.Core/XmlDocumentationGenerator.cs
  src/Refitter.SourceGenerator/README.md
  src/Refitter.Tests/SwaggerPetstoreTests.cs
  src/Refitter.Tests/XmlDocumentationGeneratorTests.cs
  src/Refitter/README.md
Labels: documentation, enhancement, .NET

#283 Fixed operation name generation names when it has illegal symbols
  src/Refitter.Core/IdentifierUtils.cs
  src/Refitter.Core/OperationNameGenerator.cs
  src/Refitter.Tests/IllegalSymbolsTests.cs
  src/Refitter.Tests/Refitter.Tests.csproj
  src/Refitter.Tests/Resources/EmbeddedResources.cs
  src/Refitter.Tests/Resources/SampleOpenSpecifications.cs
  src/Refitter.Tests/Resources/V3/SwaggerIllegalPaths.json
  src/Refitter.Tests/Resources/V3/SwaggerIllegalTitle.json
Labels: enhancement, .NET

#286 Add return type override setting.
  README.md
  docs/docfx_project/articles/refitter-file-format.md
  src/Refitter.Core/RefitInterfaceGenerator.cs
  src/Refitter.Core/RefitMultipleInterfaceByTagGenerator.cs
  src/Refitter.Core/RefitMultipleInterfaceGenerator.cs
  src/Refitter.Core/Settings/RefitGeneratorSettings.cs
  src/Refitter.Core/XmlDocumentationGenerator.cs
  src/Refitter.SourceGenerator/README.md
  src/Refitter.Tests/SwaggerPetstoreTests.cs
  src/Refitter.Tests/XmlDocumentationGeneratorTests.cs
  src/Refitter/README.md
Labels: enhancement, .NET

#285 Align file format and output examples in docs
  README.md
  docs/docfx_project/articles/examples.md
  docs/docfx_project/articles/refitter-file-format.md
  src/Refitter/README.md
Labels: documentation

#292 Add support for multiple target frameworks
  .github/workflows/regression-tests.yml
  .github/workflows/smoke-tests.yml
  README.md
  docs/docfx_project/articles/cli-tool.md
  src/Refitter/README.md
  src/Refitter/Refitter.csproj
Labels: enhancement

#295 fix: AliasAs attribute generation for StreamPart type
  src/Refitter.Core/ParameterExtractor.cs
Labels: enhancement, .NET

#298 Added Optional Setting to name the IServiceCollection Extension Method
  src/Refitter.Core/DependencyInjectionGenerator.cs
  src/Refitter.Core/Settings/DependencyInjectionSettings.cs
Labels: enhancement, .NET

#304 Fix response type always nullable under `generateNullableReferenceTypes`
  src/Refitter.Core/RefitInterfaceGenerator.cs
  src/Refitter.Tests/SwaggerPetstoreTests.cs
Labels: enhancement, .NET

#306 chore: fix typo
  src/Refitter.Core/README.md
Labels: documentation
