Repository christianhelle/refitter, pull requests merged in 2024-12, with the labels that each got.

#548 MSBuild Custom Task
  .github/workflows/msbuild.yml
  .gitignore
  src/Refitter.MSBuild/README.md
  src/Refitter.MSBuild/Refitter.MSBuild.csproj
  src/Refitter.MSBuild/Refitter.MSBuild.props
  src/Refitter.MSBuild/Refitter.MSBuild.targets
  src/Refitter.MSBuild/RefitterGenerateTask.cs
  src/Refitter.sln
  test/MSBuild/Program.cs
  test/MSBuild/Refitter.MSBuild.Tests.csproj
  test/MSBuild/build.ps1
  test/MSBuild/petstore.refitter
Labels: enhancement, .NET

#550 Add support for disabling telemetry from MSBuild task
  src/Refitter.MSBuild/Refitter.MSBuild.targets
  src/Refitter.MSBuild/RefitterGenerateTask.cs
  test/MSBuild/Refitter.MSBuild.Tests.csproj
Labels: enhancement, .NET

#552 MSBuild Documentation
  README.md
  docs/docfx_project/articles/msbuild.md
  docs/docfx_project/articles/refitter-file-format.md
  docs/docfx_project/articles/toc.yml
  src/Refitter.MSBuild/README.md
Labels: documentation

#554 Added support for custom date format
  README.md
  src/Refitter.Core/ParameterExtractor.cs
  src/Refitter.Core/Settings/CodeGeneratorSettings.cs
  src/Refitter.SourceGenerator/README.md
  src/Refitter.Tests/Examples/CustomDateFormatTests.cs
  src/Refitter/README.md
Labels: enhancement, .NET

#558 Less strict OpenAPI Validation rules
  test/OpenAPI/v3.0/weather.json
  test/smoke-tests.ps1
Labels: enhancement

#561 Fix -v|--version CLI tool argument
  src/Refitter/GenerateCommand.cs
  test/smoke-tests.ps1
Labels: enhancement

#562 Added simple logic to make most identifier strings valid
  src/Refitter.Core/IdentifierUtils.cs
  src/Refitter.Tests/Examples/OperationIdWithInvalidFirstCharTests.cs
Labels: enhancement

#563 Remove full code output examples from README
  README.md
  docs/ByEndpointOutput.cs
  docs/DefaultOutput.cs
  docs/DynamicQueryStringParameters.cs
  docs/IApiResponseOutput.cs
Labels: documentation

#564 Limit Exceptionless telemetry
  src/Refitter/Analytics.cs
  src/Refitter/GenerateCommand.cs
Labels: enhancement, .NET

#572 Show Deserializaton Errors from Source Generator
  src/Refitter.SourceGenerator/RefitterSourceGenerator.cs
Labels: enhancement, .NET
