Repository christianhelle/refitter, pull requests merged in 2024-07, with the labels that each got.

#409 Add support for generating immutable records
  src/Refitter.Core/CSharpClientGeneratorFactory.cs
  src/Refitter.Tests/CustomCSharpGeneratorSettingsTests.cs
  test/MauiExample/petstore.refitter
  test/MinimalApi/petstore.refitter
  test/petstore.refitter
Labels: enhancement, .NET

#413 Add optional RefitterSettings in generated IoC registration code
  src/Refitter.Core/DependencyInjectionGenerator.cs
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreMultipleInterfaces.g.cs
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreSingleInterfaceWithHttpResilience.g.cs
  src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreSingleInterfaceWithPolly.g.cs
  src/Refitter.Tests/DependencyInjectionGeneratorWithMicrosoftHttpResilienceTests.cs
  src/Refitter.Tests/DependencyInjectionGeneratorWithPollyTests.cs
Labels: enhancement

#414 Add Dependency Injection section to docs
  README.md
  docs/docfx_project/articles/using-the-generated-code.md
  src/Refitter/README.md
  test/MinimalApi/Program.cs
Labels: documentation

#421 Revert Microsoft.CodeAnalysis.CSharp to v4.8.0 and update SourceGenerator smoke test project to use v1.1.1
  src/Refitter.SourceGenerator/Refitter.SourceGenerator.csproj
  test/SourceGenerator/Directory.Build.props
Labels: dependencies, .NET

#419 Improve telemetry for --settings-file usage
  src/Refitter/Analytics.cs
  src/Refitter/GenerateCommand.cs
Labels: enhancement, .NET

#428 Add the possibility to generate all the Apizr goodness
  src/Refitter.Core/ApizrRegistrationGenerator.cs
  src/Refitter.Core/EnumExtensions.cs
  src/Refitter.Core/ParameterExtractor.cs
  src/Refitter.Core/RefitGenerator.cs
  src/Refitter.Core/RefitInterfaceGenerator.cs
  src/Refitter.Core/RefitInterfaceImports.cs
  src/Refitter.Core/Settings/ApizrPackages.cs
  src/Refitter.Core/Settings/ApizrSettings.cs
  src/Refitter.Core/Settings/CacheProviderType.cs
  src/Refitter.Core/Settings/DependencyInjectionSettings.cs
  src/Refitter.Core/Settings/MappingProviderType.cs
  src/Refitter.Core/Settings/NamingSettings.cs
  src/Refitter.Core/Settings/RefitGeneratorSettings.cs
  src/Refitter.Tests/ApizrGeneratorWithMicrosoftHttpResilienceTests.cs
  src/Refitter.Tests/ApizrGeneratorWithPollyTests.cs
  src/Refitter.Tests/Build/ProjectFileContents.cs
  src/Refitter.Tests/DependencyInjectionGeneratorWithMicrosoftHttpResilienceTests.cs
  src/Refitter.Tests/Examples/ApizrTests.cs
  src/Refitter.Tests/RefitInterfaceImportTests.cs
  src/Refitter.Tests/SwaggerPetstoreTests.cs
  src/Refitter/GenerateCommand.cs
Labels: enhancement

#431 [Apizr] Including an xml doc param for ApizrRequestOptions parameter
  src/Refitter.Core/RefitInterfaceGenerator.cs
  src/Refitter.Core/RefitMultipleInterfaceByTagGenerator.cs
  src/Refitter.Core/RefitMultipleInterfaceGenerator.cs
  src/Refitter.Core/XmlDocumentationGenerator.cs
  src/Refitter.Tests/XmlDocumentationGeneratorTests.cs
Labels: enhancement

#432 [Apizr] Docs updated about Apizr integration
  README.md
  docs/docfx_project/articles/cli-tool.md
  docs/docfx_project/articles/examples.md
  docs/docfx_project/articles/refitter-file-format.md
  docs/docfx_project/articles/source-generator.md
  docs/docfx_project/articles/using-the-generated-code.md
  docs/docfx_project/index.md
  src/Refitter.SourceGenerator/README.md
  src/Refitter/README.md
Labels: documentation, enhancement
