Repository christianhelle/refitter, pull requests merged in 2025-01, with the labels that each got.

#577 Return null when object subtype is not found
  src/Refitter.Core/Templates/JsonInheritanceConverter.liquid
Labels: enhancement

#588 Revert "chore(deps): update dependency fluentassertions to v8"
  src/Refitter.SourceGenerator.Tests/Refitter.SourceGenerator.Tests.csproj
Labels: dependencies

#575 - #557 - discard unused union types/inheritance types via config
  src/Refitter.Core/RefitGenerator.cs
  src/Refitter.Core/SchemaCleaner.cs
  src/Refitter.Core/Settings/RefitGeneratorSettings.cs
  src/Refitter.Tests/Examples/IncludeInheritanceHierarchyTests.cs
  src/Refitter/GenerateCommand.cs
  src/Refitter/Settings.cs
Labels: enhancement

#591 Update docs for --include-inheritance-hierarchy
  README.md
  docs/docfx_project/articles/cli-tool.md
  docs/docfx_project/articles/refitter-file-format.md
  src/Refitter/README.md
Labels: documentation

#597 Remove dependency on System.Text.Json
  src/Refitter.Core/Refitter.Core.csproj
Labels: dependencies

#603 Fix ISO date format handling when dateFormat is defined in settings file
  src/Refitter.Core/ParameterExtractor.cs
  src/Refitter.Core/Settings/CodeGeneratorSettings.cs
  src/Refitter.SourceGenerator/RefitterSourceGenerator.cs
  src/Refitter.Tests/Examples/UseIsoDateFormatTests.cs
  src/Refitter/GenerateCommand.cs
Labels: enhancement, .NET

#604 Add support for custom DateTimeFormat
  src/Refitter.Core/ParameterExtractor.cs
  src/Refitter.Core/Settings/CodeGeneratorSettings.cs
  src/Refitter.Tests/Examples/UseIsoDateFormatTests.cs
Labels: enhancement, .NET
